### PR TITLE
Update all the offsets and decryptions

### PR DESCRIPTION
**Pull request by hailzfn**
They actually work

### CODE REVIEW

**Comment by serjam** [comment]
Nice, I'm assuming you tested? Also are you sure CLIENT_INFO didn't change?

**Comment by hailzfn** [comment]
yeah the decryption should be good but I forgot to update the CLIENT_INFO offset thanks for pointing that out.
Also In game after I run the program nothing shows up I have the nvida overlay installed. maybe I messed up something but all I did was build it with debug mode as a desktop app. Could you tell me what I am doing wrong?

**Comment by hailzfn** [comment]
also all of the other offsets should work

**Comment by serjam** [comment]
> 
> 
> yeah the decryption should be good but I forgot to update the CLIENT_INFO offset thanks for pointing that out.
> Also In game after I run the program nothing shows up I have the nvida overlay installed. maybe I messed up something but all I did was build it with debug mode as a desktop app. Could you tell me what I am doing wrong?

I looked over my latest dump and it looks like parts of the decryption routines are incorrect (or maybe outdated already)? Regardless, I think it's best to leave the offsets/decryptions up to whoever wants to use this source to deter an influx of pasted cheats. 

RE Getting the hack working:
If you did everything correctly, you should see some green text in the top left ending with a version number.  Just update the addresses (Page Up) and toggle the ESP (Home) when you're in a game to use the hack. 
Also, you should know this is just part of what's needed to get this hack to work as it's missing the kernel driver.

**Comment by hailzfn** [comment]
I don't really know much about developing drivers(I'm at an intermediate level of learning c++)
so would any kernel driver that can rpm and wpm work or would I have to make my own driver

**Comment by serjam** [comment]
> 
> 
> I don't really know much about developing drivers(I'm at in intermediate level learning c++)
> so would any kernel driver that can rpm and wpm work or would I have to make my own driver

For MWClap, all you need is to be able to **read** in kernel space. Specifically, look into how one would get the base address for a process module, the PEB address, and general process memory reads. Lots of good resources out there for even beginners.

**Comment by hailzfn** [comment]
Hey man I've looked at the documentation and looked on UC for posts about that but I can't figure out how to make a driver and I don't wanna paste ik getting a programs PEB is psgetprocesspeb and stuff like that but I just can make it work and its frustrating af. can you help me out?

**Pull request closed without merging**
